# Generated by Django 5.0.1 on 2024-01-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nmae',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='nmae',
            new_name='name',
        ),
    ]
