# Generated by Django 5.0.1 on 2024-02-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_nmae_category_name_rename_nmae_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='auther',
            new_name='author',
        ),
    ]
